### PR TITLE
add an example (mainly for development)

### PR DESCRIPTION
**Pull request by marten-seemann**
Not sure if people will feel comfortable with merging this, considering that we have a separate repo for all other examples. Being able to quickly run a handshake is really helpful for debugging and during development though.

### CODE REVIEW

**Comment by raulk** [comment]
I think it would make sense to include in this repo if you frame it as a diagnostics CLI tool, rather than just an example. WDYT?

**Comment by marten-seemann** [comment]
You mean by renaming the *example* directory to something else? What do you suggest?

**Comment by raulk** [comment]
Yeah, I'd rename it to `cmd` (as per go conventions), and consolidate both commands into one, if it makes sense to you:

```
$ tlsdiag client -p ...
$ tlsdiag server -p ...
```

**Comment by marten-seemann** [comment]
@raulk: Thanks for the suggestion. I wasn't aware of this convention.

I consolidated both commands into one, due to Go's weird `flag` package this requires the following hack: https://github.com/libp2p/go-libp2p-tls/pull/14/files#diff-90f9094b324522b806a2926a9e42d244R18.
It's not production code, so that might be ok for now...

**Review by raulk — APPROVED** [review]
@marten-seemann could you rename the `cmd/cmdimpl` package to `cmd/tlsdiag` for consistency? Other than that, LGTM. go-libp2p-peer is gx-imported transitively, that's why the build doesn't fail in CI.

**Comment by marten-seemann** [comment]
> go-libp2p-peer is gx-imported transitively, that's why the build doesn't fail in CI.

Is that something that needs to be fixed? Should I add go-libp2p-peer to the `package.json`?

**Comment by raulk** [comment]
@marten-seemann I don't think it's important; it was more a "note to myself" 😛

**Pull request merged**
