### PR TITLE
Remove x/sys/cpu reference when building for js

### PR DESCRIPTION
**Pull request by paralin**
Fixes the build with "gopherjs build -v"

### CODE REVIEW

**Comment by paralin** [comment]
cc @marten-seemann  :)

**Review by marten-seemann — CHANGES_REQUESTED** [review]
https://go-review.googlesource.com/c/go/+/314609/ (which was included in Go 1.17) removed the ordering of cipher suites, and `tls.Config.PreferServerCipherSuites` is now ignored.

Since we'll be dropping support for Go 1.16 in a week or so, we can probably just remove this code path.

**Comment by paralin** [comment]
@marten-seemann What happens if someone who happens to have go 1.16 installed builds it?

**Comment by marten-seemann** [comment]
We have the policy to support the latest two Go releases. This allows us to move on and make use of new language features. If somebody decides to use an old Go release, in general all bets are off.
In this case, the consequences are very minor: they might prefer a cipher suite that's not optimized for their CPU architecture. I think we can live with that :)

**Comment by BigLep** [comment]
Closing since we no longer support go 1.16

**Comment by BigLep** [comment]
We'll create a statement in libp2p/go-libp2p about go version support.  (We support the last two versions.)

**Comment by paralin** [comment]
I get that it's not supported, but if it's not supported either way, why not just merge this and fix the build so I can get rid of my replace statements?

**Comment by marten-seemann** [comment]
@paralin It makes thing (slightly) more complicated, as it adds 2 files.
I know this doesn't sound like a lot, but things like these add up and we have to draw a line somewhere. And doing something for an unsupported Go version is pretty clearly beyond that line, no matter how small the change.

**Comment by paralin** [comment]
It adds two shim files which only build against gopherjs and serve to fix the build,

It's unsupported anyway,

Seems illogical to not just merge that. 

But you have your policies and I understand that.

**Pull request closed without merging**
