### PR TITLE
use TLS 1.3

### LINKED ISSUE #3: use TLS 1.3
We have two options here:

1. use tls-tris (with some minimal, trivial modifications, to make it work with the standard Go compiler)
2. wait until the Go standard library adds support for TLS 1.3

Note that adding support for TLS 1.3 is inherently backwards compatible, since TLS handles version negotiation itself.

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #3.

### CODE REVIEW

**Review by vyzo — COMMENTED** [review]
so does this work with go1.11?

**Comment by marten-seemann** [comment]
No, it's using the standard library TLS 1.3 implementation, which is one of the new features of Go 1.12.

**Comment by marten-seemann** [comment]
I'd like to point out that we're currently not using this code in production yet, so merging this PR shouldn't break anybody's build. I'm currently working on a way to use TLS 1.3 in production (which will also works for Ed25519 keys), but that will definitely won't be production-ready before the release of Go 1.12.

**Comment by marten-seemann** [comment]
This PR should be ready for review & merge now.

**Review by vyzo — APPROVED** [review]
LGTM

**Pull request merged**
